### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ROBERT-MCDOWELL**
Haxelib is another way to convert numerous different language to Haxe, including AS2/AS3
https://lib.haxe.org/p/refactor

### CODE REVIEW

**Comment by ROBERT-MCDOWELL** [comment]
A promising As3 to Js transpiler
https://as3js.org/

**Comment by pakastin** [comment]
Could you change the text to passive-form. I mean you shouldn't reference to yourself. Thanks!

**Comment by ROBERT-MCDOWELL** [comment]
I tried it but git didn't allow me to pull any request to you...

**Comment by ROBERT-MCDOWELL** [comment]
tell me to do it so thanks

**Pull request closed without merging**
